"use client";
import React, { useState, useEffect } from 'react';

// ==========================================
// 1. ELITE DATA STRUCTURE
// ==========================================
interface Option {
  id: string;
  text: string;
}

interface Question {
  id: string;
  text: string;
  options: Option[];
  correctOptionId: string;
}

export default function OnlineMCQInterface() {
  const questions: Question[] = [
    {
      id: "Q-001",
      text: "If a system is entirely governed by deterministic mathematical laws, what is the exact nature of human free will within that system?",
      options: [
        { id: "A", text: "It is an absolute illusion generated by biological complex systems." },
        { id: "B", text: "It exists as a quantum probability until observed by consciousness." },
        { id: "C", text: "It is mathematically compatible through non-linear chaotic dynamics." },
        { id: "D", text: "Determinism and free will operate in mutually exclusive dimensional planes." }
      ],
      correctOptionId: "B"
    },
    {
      id: "Q-002",
      text: "In the context of the physical universe, what does the speed of light (c) fundamentally represent?",
      options: [
        { id: "A", text: "The maximum speed of an accelerated mass." },
        { id: "B", text: "The speed of causality and information transfer." },
        { id: "C", text: "A relative constant dependent on the observer's frame." },
        { id: "D", text: "The limit of electromagnetic wave propagation only." }
      ],
      correctOptionId: "B"
    }
  ];

  // ==========================================
  // 2. STATE ENGINE (Day 38)
  // ==========================================
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, string>>({});
  
  const TOTAL_TIME = 120; // 2 Minutes
  const [timeLeft, setTimeLeft] = useState(TOTAL_TIME);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [cheatWarnings, setCheatWarnings] = useState(0);

  // Timer Hook
  useEffect(() => {
    if (isSubmitted || timeLeft <= 0) {
      if (timeLeft <= 0 && !isSubmitted) submitPaper();
      return;
    }
    const timer = setInterval(() => setTimeLeft((prev) => prev - 1), 1000);
    return () => clearInterval(timer);
  }, [timeLeft, isSubmitted]);

  // Anti-Cheat Hook
  useEffect(() => {
    const handleVisibilityChange = () => {
      if (document.hidden && !isSubmitted) {
        setCheatWarnings((prev) => prev + 1);
        alert("WARNING: Tab switching detected. This incident has been logged.");
      }
    };
    document.addEventListener("visibilitychange", handleVisibilityChange);
    return () => document.removeEventListener("visibilitychange", handleVisibilityChange);
  }, [isSubmitted]);

  // ==========================================
  // 3. AUTO-GRADING LOGIC (Day 39)
  // ==========================================
  const getGradingResults = () => {
    let correct = 0;
    let wrong = 0;
    let unattempted = 0;
    
    questions.forEach((q) => {
      const ans = selectedAnswers[q.id];
      if (!ans) unattempted++;
      else if (ans === q.correctOptionId) correct++;
      else wrong++;
    });

    const percentage = Math.round((correct / questions.length) * 100);
    return { correct, wrong, unattempted, percentage };
  };

  const currentQ = questions[currentIndex];

  const handleSelect = (optionId: string) => {
    if (isSubmitted) return;
    setSelectedAnswers({ ...selectedAnswers, [currentQ.id]: optionId });
  };

  const nextQuestion = () => {
    if (currentIndex < questions.length - 1) setCurrentIndex(currentIndex + 1);
  };

  const prevQuestion = () => {
    if (currentIndex > 0) setCurrentIndex(currentIndex - 1);
  };

  const submitPaper = () => {
    setIsSubmitted(true);
    // Real-world scenario: Send 'selectedAnswers' to backend API here
  };

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60).toString().padStart(2, '0');
    const s = (seconds % 60).toString().padStart(2, '0');
    return `${m}:${s}`;
  };

  const results = isSubmitted ? getGradingResults() : null;

  return (
    <>
      <style>{`
        .option-card { transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1); border: 1px solid rgba(255, 255, 255, 0.05); }
        .option-card:hover { background: rgba(168, 85, 247, 0.08); border-color: rgba(168, 85, 247, 0.4); transform: translateX(8px); }
        .option-selected { background: rgba(168, 85, 247, 0.15) !important; border-color: #a855f7 !important; box-shadow: 0 0 20px rgba(168, 85, 247, 0.2); }
        .nav-btn { transition: all 0.2s ease; }
        .nav-btn:hover:not(:disabled) { background: #a855f7; color: white; }
        .nav-btn:disabled { opacity: 0.3; cursor: not-allowed; }
        .timer-danger { color: #ef4444; animation: pulse 1s infinite; text-shadow: 0 0 10px rgba(239, 68, 68, 0.5); }
        @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.5; } 100% { opacity: 1; } }

        /* Print Logic remains identical and fully functional */
        @media print {
          body { background: white !important; color: black !important; }
          .no-print { display: none !important; }
          .print-only { display: block !important; }
          .answer-key-sheet { page-break-before: always; margin-top: 40px; }
          .print-question { margin-bottom: 30px; page-break-inside: avoid; }
          .print-options { margin-left: 20px; }
          .print-option { margin-bottom: 8px; font-size: 14px; }
          .key-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          .key-table th, .key-table td { border: 1px solid #000; padding: 10px; text-align: left; }
          .key-table th { background-color: #f0f0f0; }
        }
      `}</style>

      <div className="no-print" style={{ minHeight: '100vh', background: '#050505', color: '#FAFAFA', fontFamily: 'Inter, sans-serif', display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '40px 20px' }}>
        
        {/* Header */}
        <div style={{ width: '100%', maxWidth: '900px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '40px', borderBottom: '1px solid rgba(168, 85, 247, 0.2)', paddingBottom: '20px' }}>
          <div>
            <h1 style={{ fontSize: '24px', fontWeight: '900', letterSpacing: '2px', margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
              ZeeShaoor<span style={{ color: '#a855f7' }}>.pk</span>
            </h1>
            <div style={{ fontSize: '12px', color: '#71717A', marginTop: '5px' }}>
              Warnings Logged: <span style={{ color: cheatWarnings > 0 ? '#ef4444' : '#10b981' }}>{cheatWarnings}</span>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '10px' }}>
            <div className={timeLeft <= 60 && !isSubmitted ? "timer-danger" : ""} style={{ fontSize: '24px', fontWeight: '900', letterSpacing: '2px', fontFamily: 'monospace', color: isSubmitted ? '#10b981' : 'inherit' }}>
              {isSubmitted ? "ASSESSMENT LOCKED" : formatTime(timeLeft)}
            </div>
            {!isSubmitted && (
              <div style={{ fontSize: '12px', fontWeight: 'bold', color: '#a855f7', letterSpacing: '2px', background: 'rgba(168, 85, 247, 0.1)', padding: '6px 12px', borderRadius: '20px' }}>
                Q: {currentIndex + 1} / {questions.length}
              </div>
            )}
          </div>
        </div>

        {/* DYNAMIC VIEW SWITCHING: EXAM vs RESULTS */}
        {!isSubmitted ? (
          <>
            {/* The Exam Matrix */}
            <div style={{ width: '100%', maxWidth: '900px', flex: 1 }}>
              <h2 style={{ fontSize: '32px', fontWeight: '800', lineHeight: '1.5', marginBottom: '40px' }}>
                <span style={{ color: '#a855f7', marginRight: '15px' }}>{currentIndex + 1}.</span>
                {currentQ.text}
              </h2>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                {currentQ.options.map((opt) => {
                  const isSelected = selectedAnswers[currentQ.id] === opt.id;
                  return (
                    <div 
                      key={opt.id} onClick={() => handleSelect(opt.id)}
                      className={`option-card ${isSelected ? 'option-selected' : ''}`}
                      style={{ padding: '25px', background: 'rgba(20, 20, 20, 0.6)', borderRadius: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '20px' }}
                    >
                      <div style={{ width: '40px', height: '40px', borderRadius: '8px', background: isSelected ? '#a855f7' : '#27272A', color: isSelected ? '#fff' : '#A1A1AA', display: 'flex', justifyContent: 'center', alignItems: 'center', fontSize: '18px', fontWeight: 'bold' }}>
                        {opt.id}
                      </div>
                      <span style={{ fontSize: '18px', color: isSelected ? '#fff' : '#D4D4D8', lineHeight: '1.6' }}>{opt.text}</span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Bottom Navigation */}
            <div style={{ width: '100%', maxWidth: '900px', display: 'flex', justifyContent: 'space-between', marginTop: '50px', paddingTop: '20px', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
              <button onClick={prevQuestion} disabled={currentIndex === 0} className="nav-btn" style={{ padding: '15px 30px', background: 'transparent', border: '1px solid rgba(255,255,255,0.2)', color: '#fff', borderRadius: '8px', fontWeight: 'bold' }}>
                &#8592; PREVIOUS
              </button>
              
              <div style={{ display: 'flex', gap: '15px' }}>
                <button onClick={() => window.print()} className="nav-btn" style={{ padding: '15px 30px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: '#A1A1AA', borderRadius: '8px', fontSize: '14px', fontWeight: 'bold', letterSpacing: '1px' }}>
                  PRINT PAPER
                </button>
                <button onClick={submitPaper} className="nav-btn" style={{ padding: '15px 30px', background: '#ef4444', border: 'none', color: '#fff', borderRadius: '8px', fontSize: '14px', fontWeight: 'bold', letterSpacing: '1px', boxShadow: '0 0 20px rgba(239, 68, 68, 0.4)' }}>
                  LOCK & SUBMIT
                </button>
              </div>

              <button onClick={nextQuestion} disabled={currentIndex === questions.length - 1} className="nav-btn" style={{ padding: '15px 40px', background: 'rgba(168, 85, 247, 0.1)', border: '1px solid #a855f7', color: '#a855f7', borderRadius: '8px', fontWeight: 'bold' }}>
                NEXT &#8594;
              </button>
            </div>
          </>
        ) : (
          /* ========================================== */
          /* THE RESULTS MATRIX (Day 39 Auto-Graded UI) */
          /* ========================================== */
          <div style={{ width: '100%', maxWidth: '900px', animation: 'fadeIn 1s ease-in' }}>
            <div style={{ textAlign: 'center', marginBottom: '50px' }}>
              <div style={{ fontSize: '14px', color: '#a855f7', letterSpacing: '4px', textTransform: 'uppercase', marginBottom: '10px' }}>Truth Index Calculated</div>
              <div style={{ fontSize: '90px', fontWeight: '900', color: results?.percentage && results.percentage >= 80 ? '#10b981' : (results?.percentage && results.percentage >= 50 ? '#eab308' : '#ef4444'), textShadow: '0 0 40px rgba(168, 85, 247, 0.3)', lineHeight: '1' }}>
                {results?.percentage}%
              </div>
            </div>

            <div style={{ display: 'flex', gap: '20px', marginBottom: '50px' }}>
              <div style={{ flex: 1, background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)', padding: '20px', borderRadius: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '30px', fontWeight: '900', color: '#10b981' }}>{results?.correct}</div>
                <div style={{ fontSize: '12px', color: '#A1A1AA', textTransform: 'uppercase', letterSpacing: '1px' }}>Correct (Truth)</div>
              </div>
              <div style={{ flex: 1, background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)', padding: '20px', borderRadius: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '30px', fontWeight: '900', color: '#ef4444' }}>{results?.wrong}</div>
                <div style={{ fontSize: '12px', color: '#A1A1AA', textTransform: 'uppercase', letterSpacing: '1px' }}>Incorrect (Illusion)</div>
              </div>
              <div style={{ flex: 1, background: 'rgba(255, 255, 255, 0.05)', border: '1px solid rgba(255, 255, 255, 0.1)', padding: '20px', borderRadius: '12px', textAlign: 'center' }}>
                <div style={{ fontSize: '30px', fontWeight: '900', color: '#FAFAFA' }}>{results?.unattempted}</div>
                <div style={{ fontSize: '12px', color: '#A1A1AA', textTransform: 'uppercase', letterSpacing: '1px' }}>Unattempted</div>
              </div>
            </div>

            <div style={{ borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '40px' }}>
              <h3 style={{ fontSize: '20px', fontWeight: '800', marginBottom: '20px', color: '#a855f7' }}>Detailed Analysis</h3>
              {questions.map((q, index) => {
                const studentAns = selectedAnswers[q.id];
                const isCorrect = studentAns === q.correctOptionId;
                return (
                  <div key={q.id} style={{ background: 'rgba(20, 20, 20, 0.8)', padding: '20px', borderRadius: '12px', marginBottom: '15px', borderLeft: `4px solid ${isCorrect ? '#10b981' : '#ef4444'}` }}>
                    <div style={{ fontSize: '16px', fontWeight: 'bold', marginBottom: '15px', color: '#FAFAFA' }}>Q{index + 1}: {q.text}</div>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                      <div style={{ fontSize: '14px', color: isCorrect ? '#10b981' : '#ef4444' }}>
                        <span style={{ color: '#A1A1AA', marginRight: '10px' }}>Your Answer:</span> 
                        {studentAns ? `Option ${studentAns}` : 'None'} {isCorrect ? '✓' : '✗'}
                      </div>
                      {!isCorrect && (
                        <div style={{ fontSize: '14px', color: '#10b981', fontWeight: 'bold' }}>
                          <span style={{ color: '#A1A1AA', marginRight: '10px', fontWeight: 'normal' }}>Absolute Truth:</span> 
                          Option {q.correctOptionId}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* PAPER & ANSWER KEY (Visible ONLY on Print) */}
      <div className="print-only" style={{ display: 'none', padding: '40px', fontFamily: 'Times New Roman, serif' }}>
         {/* Print UI logic */}
         <div style={{ textAlign: 'center', borderBottom: '2px solid #000', paddingBottom: '20px', marginBottom: '40px' }}>
          <h1 style={{ margin: '0 0 10px 0', fontSize: '32px', textTransform: 'uppercase' }}>ZeeShaoor.pk</h1>
          <h2 style={{ margin: '0', fontSize: '18px', fontStyle: 'italic' }}>Awakening Intellect, Anchoring Truth</h2>
          <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'space-between', fontSize: '14px', fontWeight: 'bold' }}>
            <span>Student Name: _______________________</span>
            <span>Date: ____________</span>
            <span>Marks: ____________</span>
          </div>
        </div>

        <div className="paper-content">
          {questions.map((q, index) => (
            <div key={q.id} className="print-question">
              <h3 style={{ fontSize: '16px', margin: '0 0 15px 0' }}>Q{index + 1}. {q.text}</h3>
              <div className="print-options">
                {q.options.map(opt => (
                  <div key={opt.id} className="print-option">( {opt.id} ) {opt.text}</div>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div className="answer-key-sheet">
          <div style={{ textAlign: 'center', borderBottom: '2px solid #000', paddingBottom: '10px', marginBottom: '20px' }}>
            <h1 style={{ margin: 0, fontSize: '24px', textTransform: 'uppercase' }}>Confidential Answer Key</h1>
          </div>
          <table className="key-table">
            <thead>
              <tr><th>Question No.</th><th>Question ID</th><th>Correct Option</th></tr>
            </thead>
            <tbody>
              {questions.map((q, index) => (
                <tr key={q.id}><td>{index + 1}</td><td>{q.id}</td><td style={{ fontWeight: 'bold' }}>{q.correctOptionId}</td></tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}